- keepercommander/cli.py
- keepercommander/params.py
You can now specify the number of seconds between running all the commands. This allows basic scheduling with the configuration retained in memory only.
> Adding time delay parameter for scheduling commands

- keepercommander/__init__.py
- keepercommander/api.py
- keepercommander/plugins/windows/README.md
- keepercommander/plugins/windows/windows.py
pexpect does not work on Windows, switched to subprocess.
Also, windows net command cannot process certain characters in the
password string, so those are stripped out, which required a
modification to password rotation code.
> Windows plugin fix

- keepercommander/__init__.py
- keepercommander/cli.py
- tests/test_cli.py
Exposing rotate functionality previously available only from keeper
shell as a cli command. Example: keeper rotate —match=“MySQL Dev”
> Rotate cli command

- keepercommander/api.py
- keepercommander/record.py
Two fixes:
- If record comes with null's instead of text, it is properly read
- If RSA key comes shorter than 256 bytes, it is left padded with 0's preventing decryption error
> RSA decoding and null conversion bug fixes

- keepercommander/api.py
Incremented client version to 12.0.0.
Updated to be compatible with Keeper v12 encryption.
> Keeper v12 encryption

- keepercommander/cli.py
So that the text 'Enter password for ...' doesn't end up in the standard output.
At the moment, when I do `keeper get MYUID --format json > mysecret.json`, the json file looks like this:
```
Enter password for you@me.com
{
"record_uid": "MYUID",
"title": "my secret note",
"notes": "a very secret note"
}
```
The prompt text makes it hard to parse the JSON, hence this change.
> Use logging instead of print in password prompt

- keepercommander/cli.py
It seems like `keeper --batch-mode shell` is intended for use in
scripts -- one pipes commands to it -- but the stdout currently contains
a bunch of junk intended for humans: the welcome banner and the prompt
(e.g. `Keeper> `).  Now we suppress both in batch-mode shell.  This
allows running fun commands like
```
cat <<EOF | keeper --config ... --batch-mode shell | jq -r .password
get <UID> --format=json
get <UID> --format=json
EOF
```
to get many passwords at once.
> Make batch mode shell a little quieter

- requirements.txt
- setup.py
This commit is related to issue #265
> Specifying version for `prompt-toolkit` and python >= 3.5

- keepercommander/__init__.py
- keepercommander/commands/enterprise.py
- keepercommander/commands/utils.py
- keepercommander/plugins/azureadpwd/azureadpwd.py
- registering data key when persistent login is turned on
- added aliases for `this-device`: `ip-auto-approve` and `persistent-login`
- updated message text for azure ad plugin
- new fields and export functionality for `device-approve` command
> Minor improvements to persistent login, documentation, and device-aprove

- README.md
- keepercommander/commands/register.py
- keepercommander/commands/utils.py
- keepercommander/importer/csv/csv.py
- keepercommander/plugins/commands.py
- keepercommander/plugins/ssh/ssh.py
- added more detailed error when plugin failed to execute
- added uid to the csv export
- removed documentation to disable login v3
- `share-folder` command: added force capability to ignore default folder permissions when initially sharing a record
- `share-report` command: added flat `share-report` to include date the record was shared
- `whoami` command: fixed error displaying storage used
> Enhancements

- README.md
- keepercommander/__main__.py
I'd like to put something like in my shell's rc file, or maybe at the root of a deep git repo:
```
export KEEPER_CONFIG_FILE="$one_central_safe_place/.keeperrc.json"
```
Then I can run `keeper` anywhere in the filesystem and it'll always use that `.keeperrc.json` for reading / caching credentials.
I could see this as dangerous for a novice who might not realize they have very important credentials stored perhaps unprotected in clear text, but this tool seems to be targeted at tech professionals who ought to know how to take measured risks and what's safe and what's not.
I'll admit though I'm only barely familiar with KeeperCommander's API, so perhaps there's a security issue here I'm overlooking? Or is this a safe convenience to add?
Thanks,
DCM
> Allow specifying path to config file as environment variable KEEPER_CONFIG_FILE

- keepercommander/importer/commands.py
Implementing capability to don't allow user to perform `export` if user enterprise permissions restrict that.
Similar warning in the Web Vault
> Adding export restriction

- keepercommander/__init__.py
- keepercommander/commands/utils.py
- keepercommander/rest_api.py
- bumping version to 4.83 (code and api)
- making `version` command not requiring user to be logged in
> Bumping version

- Makefile
- keepercommander/api.py
- keepercommander/importer/commands.py
- keepercommander/importer/imp_exp.py
- keepercommander/rest_api.py
- pylintrc
go rule becomes report rule. pylint exit status is ignored
Parse and pass around update/update_flag
Many small linter fixes. Attempts to update records through older/import_folders_and_records and fails.  Added result status output
Introduced PYTHON_FILES variable, rather than computing it in multiple rules
A little refactoring to simplify matters
import appears to work, but no --update at all.
import --update works for a single update record
Misc.
Split some code out into functions.
Decoupled import-or-update-control from the import-and-update.
Works on import and at least one update.
Eliminated most FIXMEs
Improved error reporting a bit. Replaced a manual hashlib use with build_record_hash
Added 2 FIXME's and a comment about an assert
Added authentication data to execute_update_record. …
> Added --update option to import command.

- keepercommander/commands/recordv3.py
This is needed for https://keeper.atlassian.net/browse/KC-237
There is a missing return value in commands.recordv3.RecordAddCommand.execute() when the condition `is_v2 or (not v3_enabled and not has_v3_options)` is True. This was causing test_commands.py to fail.
> The execute method of commands.recordv3.RecordAddCommand should return a record uid when is_v2 == True

- keepercommander/cli.py
- keepercommander/constants.py
- Fix the ksm command by using shlex.split on the command line that is passed to subprocess.check_call (This is only needed on non-Windows platforms)
- Add more info to the error message that is returned if ksm is not installed, i.e. a URL that provides installation instructions for ksm
- Don't display the output of the `which ksm` or `where ksm` that is used to determine if ksm is installed
> Fix ksm (KC-256)

- keepercommander/commands/recordv3.py
- Update the help for clipboard-copy to show the alias "cc"
- Add the "--copy-uid/-cu" option to copy the record UID
- Add better output to the clipboard-copy to show what was copied to clipboard, i.e. "Password", "Login", or "Record UID"
> Add --copy-uid option to clipboard-copy (KC-253)

- keepercommander/commands/folder.py
- unit-tests/test_command_folder.py
Make the mkdir of a preexisting directory log a warning instead of an info, and change the corresponding unit test to match.
> Failing mkdir test

- requirements.txt
- setup.py
Setting Python version to 3.6
Setting version of cryptography to be >= 3.4.8
> Setting Python and cryptongraphy versions

- .github/workflows/test-with-pytest.yml
- setup.py
This is a follow up to #487 for KC-244
- Fix an error in the setup.py from #487 
- Update the GitHub actions to install all Commander dependencies and run all non-integration tests
- Run the GitHub actions on all pull requests and pushes to master
- Also run the tests on Windows
There is still the need to add a Keeper account in order to run the integration tests. This can happen in another PR.
I'm not running the tests on Mac because as far as I understand it is much more expensive. Perhaps we want a custom Github action test runner for this?
> Finish PR tests (KC-244)

- setup.py
This is a follow-up to #487 and #490
This PR re-adds libkeepass to the install_requires parameter in setup.py and removes the extras_require keepass option.
It had previously been discussed that libkeepass should be installed with keepercommander by default.
> Make libkeepass a default dependency in setup.py

- keepercommander/importer/lastpass/lastpass.py
If a Lastpass record being imported has no title then the import will crash. ~This PR adds in a default of "Lastpass Import Untitled [count]" for each untitled record being imported.~
The records that didn't have titles had "http://group" in the URL because they were folders. This PR skips those items.
> Fix lastpass import of records without title

- keepercommander/importer/lastpass/fetcher.py
- keepercommander/importer/lastpass/lastpass.py
- keepercommander/importer/lastpass/shared_folder.py
- keepercommander/importer/lastpass/vault.py
- Adds class LastpassSharedFolder to store shared folder name with permissions for shared folder imported from Lastpass.
- Makes API call to Lastpass to retrieve shared folder permissions which are stored in Vault.shared_folders as list of LastpassSharedFolder.
- Yield list of importer.SharedFolder to the Keeper import with permissions populated from the lastpass shared folders.
> Import shared folder members with shared folder (KC-286)

- keepercommander/importer/imp_exp.py
- keepercommander/importer/lastpass/fetcher.py
- keepercommander/importer/lastpass/lastpass.py
- keepercommander/importer/lastpass/shared_folder.py
- keepercommander/importer/lastpass/vault.py
This PR returns the team names as well as users that have access to the shared folder being imported. The team permissions are added as an attribute to the LastpassSharedFolder, but the permissions for the teams are still not being imported into Keeper.
> Store Lastpass shared folder teams in LastpassSharedFolder

- keepercommander/__main__.py
This PR fixes the logging level when using the option `-lwsc=true`. For some reason when this option is true, `logging.basicConfig` does not set the logging level according to the `level` parameter that is passed. The workaround is to use a separate `logging.getLogger().setLevel` to set the correct logging level.
On further investigation, the reason `logging.basicConfig` doesn't work in some situations is because of the following in the documentation:
>This function does nothing if the root logger already has handlers configured, unless the keyword argument force is set to True.
> Fix logging level when using "-lwsc=true" (KC-290)

- keepercommander/commands/utils.py
`sm app get AppName` is not printing Permissions status for each Share type. Example output:
> Printing editable status of the shares when listing application details

- keepercommander/importer/imp_exp.py
This is a fix for getting the correct field size for large records from LastPass
> Get correct field size for large records from LastPass

- keepercommander/api.py
- keepercommander/importer/commands.py
- keepercommander/importer/imp_exp.py
- keepercommander/importer/lastpass/attachment.py
- keepercommander/importer/lastpass/attachment_reader.py
- keepercommander/importer/lastpass/lastpass.py
- keepercommander/importer/lastpass/parser.py
- keepercommander/importer/lastpass/vault.py
This PR makes the following updates for imports:
- Create a new `api.update_records_v3` that updates multiple records in one API call and shares functionality with `api.update_record_v3`
- Update the `upload_v3_attachments` to use one `vault/files_add` API request for every chunk of file attachments to be uploaded with a default chunk size of 100.
- Update the `upload_v3_attachments` to use one `api.update_records_v3` call for attaching the files to records corresponding with the uploaded file attachments.
- Update the LastPass import to skip `http://group` records before checking for a missing title
- Updates the name of the temporary attachment file in the file-cache directory to be just the attachment file id which should eliminate re-downloading if there a different number or ordering …
> Import updates

- keepercommander/api.py
- keepercommander/commands/base.py
- keepercommander/commands/convert.py
- keepercommander/record_pb2.py
- keepercommander/recordv3.py
This adds a new command "convert" to convert v2 records to v3 records.
The command has the following features:
- Multiple arguments are allowed
- Each argument is a pattern to match either the title or UID of a record
- Option `--type (-t)` for specifying the type of the converted record
- Option `--dry-run (-n)` for previewing what changes would be made
- Option `--recursive (-r)` for applying recursively to subdirectories
- Option `--url (-u)` for filtering based on a pattern to match a URL or `*` for all records with a URL
> Convert v2 record to v3 record (KC-308)

- keepercommander/recordv3.py
- keepercommander/utils.py
Convert v2 field values matching a URL pattern to a v3 `url` field type and v2 field values over 128 characters to a v3 `multiline` field type.
> Convert v2 to v3 fields (KC-308)

- keepercommander/commands/utils.py
This fix adds the params argument to the `is_up_to_date_version` function call that was missing the argument.
> Fix version command (KC-316)

- keepercommander/commands/convert.py
This PR does the following with the "convert" command:
- Fixes the error handling of an attempt to convert a read-only record to v3.
- Updates the output of the "convert" command by giving a count of records matched and successfully converted along with a list of successfully converted records.
- Adds a --quiet option to suppress output besides warnings and errors
> Fix "convert" command error handling and update output

- keepercommander/commands/utils.py
- setup.py
KSM: Added ability to generate config with `appOwnerPublicKey` key for create records by Secrets Manager
> KSM: appOwnerPublicKey in config

- keepercommander/importer/imp_exp.py
This fixes an issue with the following traceback:
```
Traceback (most recent call last):
File "keepercommander/cli.py", line 547, in loop
File "keepercommander/cli.py", line 369, in do_command
File "keepercommander/importer/commands.py", line 123, in execute_args
File "keepercommander/commands/base.py", line 250, in execute_args
File "keepercommander/importer/commands.py", line 167, in execute
File "keepercommander/importer/imp_exp.py", line 806, in _import
File "keepercommander/importer/imp_exp.py", line 806, in <listcomp>
KeyError: 'FiTacTpxdnPXQLbXbAjtAg'
An unexpected error occurred: 'FiTacTpxdnPXQLbXbAjtAg'. Toggle debug to print traceback
My Vault>
```
This issue occurs when an importing a record that already exists but is missing the file attachment.
> Don't fail if file attachments are missing for existing record for import

- keepercommander/commands/utils.py
KSM: Fixed missing `KEY_OWNER_PUBLIC_KEY` property in `ConfigKeys` if KSM library is < 16.2.0
> Fixing missing KEY_OWNER_PUBLIC_KEY

- keepercommander/commands/record.py
- keepercommander/commands/recordv3.py
This PR makes it easier to view and search shared folders without showing other categories of items.
This PR also enables the verbosity option for all categories in the search in addition to record verbosity.
> Add a --categories option to the search command

- keepercommander/importer/imp_exp.py
I confirmed that this fixes errors that return the following output:
```
Error code: files_upload_fail
Communication Error: file size limit exceeded
```
> Use actual file size for vault/files_add API call

- keepercommander/base32hex.py
- keepercommander/record.py
The Python `base64.b32decode` has some issues. This new decode function was inspired by changes in the Python 3.10 version as well as https://github.com/graham/base32hex. Neither of these other b32decode functions would work perfectly as-is. I combined features from both.
> Fix b32decode for TOTP decoding

- keepercommander/importer/lastpass/parser.py
This is an untested fix for an error report with the following traceback:
> Fix TOTP parse error

- keepercommander/plugins/aws_common.py
- keepercommander/plugins/awskey/aws_accesskey.py
- keepercommander/plugins/awspswd/aws_passwd.py
- keepercommander/plugins/commands.py
- keepercommander/plugins/plugin_manager.py
- setup.py
- Use boto3 instead of subprocess call to AWS CLI
- Allow for custom update_password method for plugins not using password stored in record password field or newly generated password
- Add option "cmdr:aws_profile" to use custom profile for connection
- Add option "cmdr:aws_sync_profile" to allow for synchronizing the new key with a profile in the AWS credentials file
> Improvements to AWS rotation including using v3 records and new API

- keepercommander/commands/recordv3.py
- keepercommander/commands/utils.py
- keepercommander/generator.py
- keepercommander/plugins/commands.py
- keepercommander/plugins/plugin_manager.py
- Update KeeperPasswordGenerator to split count of password categories over remaining length when categories aren't specified
- Add class method to KeeperPasswordGenerator for getting instance from rules string
- Add --generate-rules and --generate-length option to `add` and `edit` commands
- Add --rules option to generate command as well
- Add --length or `cmdr:length` option to rotation plugins as well
> Add generate password rules options to add and edit commands (KC-388)

- keepercommander/commands/enterprise.py
- keepercommander/commands/enterprise_common.py
- keepercommander/commands/enterprise_create_user.py
- unit-tests/test_command_enterprise.py
This PR makes the following enterprise command changes:
- Add options `--add-team` (`-at`) and `--remove-team` (`-rt`) to the `enterprise-role` command
- Show teams output for the `enterprise-role` command with both `--format` options of both `json` and `text`
- Add options `--add-role` (`-ar`) and `--remove-role` (`-rr`) to the `enterprise-team` command
- Show roles output for the `enterprise-team` command
> Add capability to display and change team membership for enterprise roles (KC-396)

- keepercommander/__main__.py
config file loaded/created on start-up is now set in the following order: 
1) cmd arg 
2) ENVIRONMENT_VARIABLE
3) shortcut default
4) working directory default
> re-ordered config file setting precedence

- keepercommander/commands/aram.py
- keepercommander/sox/__init__.py
1) removed trailing slashes in URL values, 
2) all record UIDs now included in csv/json outputs 
3) added newline to end of data-download progress output to stdout,
4) fixed bug with wrong record UIDs being assigned to rows
> compliance-report readability/export fixes: 

- keepercommander/sox/sox_data.py
- keepercommander/sox/sox_types.py
loading shared-folder teams & users no longer depends on loaded sf<-->record links
> fix loading of in-memory sox data shared folder info 

- keepercommander/commands/enterprise.py
1) fix for security-audit-report --save option logic (score update now uses new SecurityReport object instead of the one provided by KA) 
2) renamed var for readability/PEP-compliance
> security-audit-report CMD improvement/fix: 

- keepercommander/breachwatch.py
- keepercommander/commands/breachwatch.py
- keepercommander/commands/enterprise.py
1) de-couple sec. score resetting from "domain" value in incremental security data 
2) remove extraneous properties from updated security data 
3) limit domain string length (to prevent issues w/ RSA encryption data size limit)
> security audit scores reset/security data update improvements: 

- keepercommander/commands/convert.py
added "--record-type" alias for "-t"/"--record_type" option
> `convert` cmd improvement (Jira KC-525): 

- keepercommander/commands/folder.py
- keepercommander/display.py
- keepercommander/recordv3.py
improvements:
1) `tree` cmd - added options for showing record nodes, share-folder permissions, title
2) `rndir` cmd - added "--quiet" option
3) recordv3 - added record title getter from cached record data
> feature: `transform-folder` cmd (Jira KC-464)

- keepercommander/commands/folder.py
- keepercommander/display.py
`transform-folder` cmd:
1) added support for transforming folders w/ space(s) in name
`tree` cmd w/ --records option:
1) root-folder records now shown 
2) record text formatted for clarity
3) nodes sorting identical to vault GUI (folders precede records for each folder node)
> `tree` and `transform-folder` improvements/fixes (Jira KC-526)

- keepercommander/commands/enterprise.py
removed returned-rows count as condition for fetching additional login-data from KA
> `user-report` fix: login-data pagination bug (Jira KC-530)

- keepercommander/commands/utils.py
disable security data updates for vaults w/ no user-owned password records
> `sync-security-data` fix/improvement (Jira KC-531): 

- keepercommander/commands/helpers/record.py
- keepercommander/commands/utils.py
`sync-security-data`: added support for 
1) pagination (for vaults w/ more than 1000 password records)
2) filter by records
3) "--quiet" option
additional improvements:
1) added helper module (includes record UID getter) for record-related tasks
> `sync-security-data` improvements and related additions:

- keepercommander/commands/record.py
- keepercommander/commands/register.py
- keepercommander/display.py
- keepercommander/subfolder.py
`shared-records-report`: 
1) added filter by containing folder, 
2) fixed bug in share-team getter, 
3) fixed shared-folder path not resolved to UID 
`tree`:
1) fixed bug w/ record-display
> `shared-records-report` & `tree` fixes/improvement (KC-535):  

- keepercommander/commands/folder.py
- keepercommander/commands/helpers/record.py
- keepercommander/commands/record.py
- keepercommander/commands/utils.py
- keepercommander/display.py
- keepercommander/subfolder.py
1. modify / add helper functions that enable resolution of folder/record paths to all associated UIDs
2. `tree` CMD improvement/fix: 
- bug fix for records/folders w/ duplicate paths not displayed in tree-structure 
- resolve folder path command args (used to filter command output) to all associated UIDs
3. `shared-records-report` improvement: filter results using all UIDs mapped to specified folder paths
4.  `sync-security-data` improvement
> record/folder path resolution and related fixes/improvements (KC-561, KC-558):

- keepercommander/display.py
check for each record's existence in user's vault before adding it to the tree-structure display
> (KC-568) `tree` fix: 

- keepercommander/commands/enterprise.py
- keepercommander/utils.py
1) add option for specifying score type ("strong_passwords" type results in score calculation and format identical to vault's),
2) match vault's definition of "weak" (strength < 40)
> `security-audit-report` improvements (KC-569): 

- keepercommander/commands/record.py
- keepercommander/commands/register.py
- keepercommander/shared_record.py
1) add support for matching on shares, 
2) fix inadvertent removal of shares upon duplicate record deletion, 
3) add support for "dry-run" mode, 
4) add support for "quiet" mode
5) limit displayed URL string length (for clarity of output)
> (KC-581/587) `find-duplicate --merge` fix/improvements:

- keepercommander/commands/register.py
- keepercommander/shared_record.py
1) add support for "@existing" pseudo-username/record value in `share-folder` (to allow setting of specified permissions for existing users and/or records
2) fix NoneType cached_team_members issue in get_shared_records() (due to deleted team member accounts)
> (KC-589) `share-folder` improvement/ fix:

- keepercommander/commands/register.py
handle `params.available_team_cache = None` exception
> (KC-581) `share-folder` fix: 

- keepercommander/shared_record.py
1) handle NoneType params.enterprise["team_users"] value exception in shared_record.get_shared_records() common function
2) clean up (remove extraneous TODO comment)
> (KC-592) `share-report`/`shared-records-report` fix/improvement: 

- keepercommander/commands/record.py
- keepercommander/shared_record.py
add support for paginated record delete requests (to address KA request obj length limit of 1000)
> (KC-598) `rm` fix/improvement: 

- keepercommander/commands/compliance.py
- keepercommander/sox/__init__.py
1) add `shared-folder-report` subcommand 
2) add `--show-team-users` option to `team-report` subcommand 
3) fix shown team->shared-folder permissions in `team-report` 
4) display number of records contained by each shared folder in `team-report` output 
5) add `stats` alias for `summary-report` subcommand
6) SOX data retrieval fix: set team share restrictions indicated in response
> `compliance` improvements/additions:

- keepercommander/commands/base.py
- keepercommander/commands/register.py
- keepercommander/sox/sox_data.py
1) added options for exporting and formatting resulting relevant data
2) added `--scope` option (w/ additional ability to expand duplicate-record search to  all enterprise vaults)
> `find-duplicate` improvements:

- keepercommander/sox/__init__.py
`--rebuild` option now clears all previously-cached non-aging compliance data
> (KC-636) compliance-data cache rebuild fix: 

- examples/complete_user_report.py
- examples/send_breachwatch_reminder.py
- keepercommander/commands/enterprise.py
- keepercommander/commands/security_audit.py
- tests/test_enterprise_commands.py
1) add new `security-audit` command w/ sub-commands 
(a) `report` (replaces `security-audit-report` cmd)
(b) `sync` -- uses KA endpoint clear_security_data to clear/reset/recalculate vault security scores admin-side
> (KC-647) `security-audit` refactor/improvements: 

- keepercommander/commands/register.py
- keepercommander/commands/security_audit.py
1) remove security-data update prior to record transfer in `share-record` 
2) remove logic for clearing summary security scores via vault-initiated security-data "hard" sync (via `ssd --hard`, to be deprecated)
> (KC-661) `share-record`/`security-audit-report` improvements: 

- keepercommander/commands/aram.py
- keepercommander/commands/enterprise.py
output wrongly indicates failed operation when action is applied successfully
> (KC-663) `action-report` fix: 

- keepercommander/commands/scim.py
I encountered unexpected users deactivation when I run 'scim push' to sync groups from google workspace to keeper enterprise.
I created a keeper vault record to sync groups described in https://docs.keeper.io/secrets-manager/commander-cli/command-reference/enterprise-management-commands/scim-push-configuration.
And I set group name which include users we expect to use keeper.(`Google #6`)
If scim_group is set in the record for scim-push config to get member list from specified group. The function `scim_group` use member list from incorrect group. The function does not search/lookup group id by group name, it use the first group of group list from google workspace.
As a result user list in keeper become not desired.
BTW, now users are provisioned by SCIM procedure. I think the `scim push` …
> Fixed scim push, multiple group and get user list from google

- keepercommander/commands/security_audit.py
username and email resolution bug w/in multiple MSP/MC contexts
> (KC-687) `security-audit-report` fix: 

- keepercommander/breachwatch.py
- keepercommander/commands/breachwatch.py
- keepercommander/commands/record.py
- keepercommander/commands/record_edit.py
- keepercommander/commands/recordv2.py
- keepercommander/commands/recordv3.py
- keepercommander/commands/utils.py
- keepercommander/params.py
- keepercommander/record_management.py
- keepercommander/sync_down.py
1) `sync-security-data` fixes / improvements 
2) add BreachWatch scan of vault (detect outdated security-data and update) on full sync-down
3) enable security-data updates for users w/ no BreachWatch add-on
4) option to force-update record security-data (security-data now only updated if older than record-modified date or non-existent, by default)
> (KC-696) BreachWatch / security-data update improvements / fixes: 

- keepercommander/shared_record.py
display no owner for owner-less records instead of current user
> (KC-701) `share-report` bug-fix: 

- keepercommander/commands/utils.py
display list of available commands if no <COMMAND> value is given in command call
> (KC-710) `help` improvement: 

- keepercommander/commands/compliance.py
- keepercommander/sox/sox_data.py
1) add total (owned + shared) items column for each vault in `compliance stats`
2) add support for loading unencrypted cached compliance data
> (KC-738) + (KC-739) compliance improvements: 

- keepercommander/commands/register.py
add flag for ignoring share permissions when merging duplicates
> (KC-737) `find-duplicate` improvement: 

- keepercommander/commands/register.py
1) added API request-batching to allow updating permissions for shared folders w/ > 500 users or records (avoiding KA exception on requests that exceed that limit)
> (KC-740) `share-folder` fix:

- keepercommander/importer/keepass/keepass.py
Force user to enter master password twice (for confirmation) when prompted to set it for an exported KeePass file
> (KC-618): `export` improvement: 

- keepercommander/commands/folder.py
1) allow non-share-admins w/ full share-permissions to do folder transform, 
2) allow transformation (and rebasing) of shared-folder subfolders, 
3) add `--clear-shares` flag to allow transforming a shared-folder or shared-folder subfolder and all its sub-folders to user-folders
4) removed record-permissions checking
> `transform-folder` bug-fixes/improvements (KC-756): 

- keepercommander/commands/discoveryrotation.py
- keepercommander/commands/tunnel/port_forward/endpoint.py
Use Krelay or overwrite that with an env var
> Tunneling use krelay

- keepercommander/commands/folder.py
Allow transformation of trees w/ folders whose names contain non-consecutive forward-slashes
> (KC-760)`transform-folder` fix: 

- keepercommander/commands/compliance.py
- keepercommander/commands/ssh_agent.py
`compliance stats`: 
- show account primary email instead of alias; 
`ssh-agent`:
- allow loading private keys w/ 444 byte-length (valid range minimum now inclusive) 
- fix signing w/ "rsa-sha2-256" key+hash
> (KC-761) `compliance stats` + `ssh-agent` fixes / improvements

- keepercommander/commands/recordv3.py
allow any record-type w/ scope = RT_ENTERPRISE to be deleted / modified (synonymous w/ custom record-type)
> `record-type` fix:

- keepercommander/api.py
- keepercommander/commands/record.py
- keepercommander/commands/register.py
`share-record`
- root-folder records can now be referenced by title
- fixed bug preventing updating of shares for records previously shared w/ same user
`get` / `trash get`
- correct record-(re)sharing permissions now shown
> (KC-769) `share-record` / `get` / `trash get` bug-fixes: 

- keepercommander/commands/register.py
bug: users/teams/records from one shared-folder are added to other shared-folders when applying permissions updates to existing records/users/teams for multiple shared-folders
> (KC-776) `share-folder` bug-fix 

- keepercommander/importer/keepass/keepass.py
add support for importing and exporting TOTP URIs using entry field "otp" (for compatibility with other PW managers)
> KeePass import/export improvement (KC-780): 

- keepercommander/breachwatch.py
- keepercommander/cli.py
- keepercommander/commands/breachwatch.py
- keepercommander/commands/helpers/enterprise.py
- keepercommander/commands/security_audit.py
- keepercommander/sox/__init__.py
- keepercommander/utils.py
- `breachwatch report`: bug-fix for inaccurate report when run in MC as MSP admin
- `compliance *`: improved messaging for denied operations
-  minor code clean-up
> `breachwatch report` + `compliance *` fixes/improvements (part of KC-790)

- keepercommander/commands/aram.py
Add support for filtering by date instead of period
> `aging-report` improvement (KC-791): 

- keepercommander/commands/security_audit.py
- keepercommander/crypto.py
1) fix for decryption of insufficiently-padded security-data 
2) support for non-interactive summary score resetting (no confirmation prompt) + minimal screen output (no security-audit report run on sync done)
> (KC-797) `security-audit report/sync` Improvements/Fixes: 

- keepercommander/commands/aram.py
fix for command premature exit when no period or cut-off date is explicitly provided
> (KC-802) `aging-report`: 

- keepercommander/commands/security_audit.py
include decrypted incremental data in report when decoding fails
> (KC-803)`security-audit-report` error-reporting improvement: 

- keepercommander/__init__.py
- keepercommander/commands/security_audit.py
Add result of decoding incremental data using detected encoding when first decoding attempt fails
> (KC-803) `security-audit-report` error-reporting improvement

- keepercommander/commands/security_audit.py
1) ignore incremental data w/ undefined strength property and flag vault for reset 
2) add support for detecting and fixing/resetting vaults w/ misaligned scores (negative unique passwords) 
3) add indicator for vaults with pending security-data sync
> (KC-809) `security-audit-report` improvements / additions:

- keepercommander/crypto.py
- unit-tests/test_crypto.py
Apply left-padding of 0s to ciphertext if shorter than expected for RSA decryption by default (unit-test included)
> (KC-814) RSA Decryption fix (app-wide): 

- keepercommander/__init__.py
- keepercommander/commands/utils.py
1. ) Initialize enterprise data before BreachWatch and security-data updates
2. ) More-detailed debug output, improved error-handling when encryption fails during security-data updates
> KC-817: LoginCommand fix/improvements

- keepercommander/__init__.py
- keepercommander/config_storage/loader.py
app configuration is no longer written to local file-system if no filename is specified (non-CLI context)
> SDK-usage improvement: 

- keepercommander/commands/discover/__init__.py
- keepercommander/commands/discover/job_remove.py
- keepercommander/commands/discover/job_status.py
- keepercommander/commands/discover/result_process.py
Commands like ...
* `pam action discover job remove`
* `pam action discover job status`
* `pam action discover process`
were calling `gateway_helper.get_all_gateways` in a loop. Change the code to call the it outside of the loop and passed the list of gateways to the `from_configuration_uid`
> DR-853 Recude Controller API calls

- keepercommander/commands/discoveryrotation.py
- keepercommander/commands/pam_service/__init__.py
- keepercommander/commands/pam_service/add.py
- keepercommander/commands/pam_service/list.py
- keepercommander/commands/pam_service/remove.py
Added the comamnds
* pam action service list
* pam action service add
* pam action service remove
These commands add graph mapping to indicate what machines a user is used for a serice or scheduled task.
> DR-892 Add commands to control the user service/task mapping

- keepercommander/commands/pam_service/add.py
- keepercommander/commands/pam_service/list.py
- keepercommander/commands/pam_service/remove.py
The add command was not stopping when the OS is not set in the machine record. Wasn't fatal, but the OS should be set in the machine record.
* Fixed command help to reference UID of record.
* Fixed the poorly written success message.
* Fixed the Service/Scheduled Task indicators. Used color to separate them, but blended together if user is not using colors.
> DR-892 Fix command not stopping on errors and message fix.

- keepercommander/commands/discover/job_start.py
- keepercommander/commands/pam/pam_dto.py
Gateway now accepts the languages. It can handle multiple, so it changed to an list.
Default changed to en_US which matches the language code returned by the translation team.
Also fix code that is not supported in Python >= 3.8.
> DR-886 Change API call from language to languages

- keepercommander/commands/discover/job_status.py
In the job detail, some vertices may no longer exist, are inactive, or missing content. Skip these with printing out information.
> DR-941 Skip unknown, inactive, or missing content vertices.

- keepercommander/importer/cyberark/cyberark.py
Use lstrip, rstrip, and split to accept pvwa_host
- with a leading https:// and/or a trailing /
- with or without a "component" like privilegecloud,
e.g., privilegecloud.cyberark.cloud
> Improve parsing/handling of the PVWA host argument.

- keepercommander/importer/cyberark/cyberark.py
- Revert to login or Password types depending on attribute availability
- Remove accidentally included barrier condition
> Support for CyberArk Accounts using Platforms that lack userName and/or address

- keepercommander/importer/cyberark/cyberark.py
Testing for empty still requires attribute existence in Python--who knew? 😳
> Bugfix: use hasattr instead of testing for empty.

- keepercommander/commands/LICENSE_CONSUMPTION_REPORT.md
- keepercommander/commands/enterprise_reports.py
Added `license-consumption-report` command to analyze feature license usage. Introduced support for PAM and other features with options for detailed views, node filtering, team inclusion, and multiple output formats.
> KC-875: Add `license-consumption-report` command

- keepercommander/display.py
**Resolves:** [Issue 1253](https://github.com/Keeper-Security/Commander/issues/1253)
Changed WARNING color for better visibility on light-themed terminals while preserving clarity on dark themes.
> Update 'warning' color for better readability

- RECORD_ADD_DOCUMENTATION.md
- keepercommander/__main__.py
- keepercommander/cli.py
- keepercommander/commands/pam_saas/__init__.py
- keepercommander/commands/pam_saas/config.py
- keepercommander/commands/pam_saas/update.py
- keepercommander/commands/record_edit.py
- keepercommander/utils.py
- unit-tests/test_cli.py
This PR adds line continuation support to Keeper Commander CLI and provides comprehensive documentation for the `record-add` command.
- **Backslash (`\`) line continuation** in CLI commands
- **Enhanced argument parsing** with whitespace normalization
- **Robust copy-paste handling** - filters empty fields from trailing spaces
- **Continuation prompt** shows `...` to indicate multi-line mode
- **Complete `record-add` documentation** with 200+ examples
- **All record types covered**: login, contact, bankCard, address, serverCredentials, sshKeys, etc.
- **Correct syntax examples**: dot notation, `$JSON:`, `$GEN`, file attachments
- **Advanced features**: password generation, TOTP, SSH key generation, self-destruct
- **Comparison with `record-update`** command
- **Troubleshooting and best …
> Craig saas improvements

- keepercommander/commands/utils.py
Resolves: [KC-922](https://keeper.atlassian.net/browse/KC-922)
Added `is_authorised()` methods returning False to `WhoamiCommand` and `KeepAliveCommand` to prevent triggering login or 2FA prompts. This allows users to check login status without initiating authentication flows.
[KC-922]: https://keeper.atlassian.net/browse/KC-922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix KC-922: To check login status without initiating authentication flows

- keepercommander/biometric/README.md
- keepercommander/biometric/client.py
- keepercommander/biometric/commands/base.py
- keepercommander/biometric/commands/list.py
- keepercommander/biometric/commands/update_name.py
- keepercommander/biometric/utils/aaguid.py
- keepercommander/biometric/utils/constants.py
This PR improves biometric credential handling and display in Keeper Commander.
- **Credential Listing Enhancements**
- Now shows credentials registered via browser (e.g., iCloud Keychain, Chrome on Mac).
- Uses AAGUID mapping to assign provider names if no friendly name is set.
- **Improved Timestamp Formatting**
- Timestamps (`created`, `last_used`) are now shown in local time format.
- Displays "Today" or "Never" where applicable.
- **Default Credential Name Update**
- Replaces platform-based names with `Commander CLI (<hostname>)`.
- Updated `README.md` and sample outputs to match these changes.
> Biometric changes: Update display name and time formats

- keepercommander/loginv3.py
Hi
This pull request changes the biometric login handling from just printing the information to the log handler.
This change has following benefits:
-  you can now pipe the output e.g. from a keeper get into another tool without getting also the biometric login information (stout vs now sterr)
- informational output is now streamlined with other warnings and information
> Changes biometric login info from print to logging

- keepercommander/commands/utils.py
- Introduced a new `login-status` command to check the current login session of the user.
- If **persistent login** is enabled, the command will display **"Logged in"**.
- If not, it will return **"Not logged in"**.
- This helps users quickly verify their login session status.
[KC-922]: https://keeper.atlassian.net/browse/KC-922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add login-status command

- keepercommander/commands/folder.py
- unit-tests/test_command_folder.py
- Modified FolderListCommand.execute() to only apply color formatting for non-JSON/CSV formats
- Added unit test to verify JSON output contains no ANSI escape sequences
- Preserves colored terminal output while ensuring clean JSON for programmatic parsing
Fixes issue where ls -l command was including escape sequences like \u001b[35m in JSON output
> Fix ls -l command to exclude ANSI color codes from JSON output

- Dockerfile
- docker-entrypoint.sh
- keepercommander/service/README.md
- Improved Docker deployment for Keeper Commander with greater usability and clearer documentation.
- Dockerfile: Updated to python:3.11-slim and added support for an entrypoint script.
- Entrypoint Script: Introduced automatic device registration, persistent login, and support for multiple authentication methods (username/password and mount-config based).
- Documentation: Streamlined examples, added a configuration file setup guide, and expanded coverage of interactive mode.
> KC-942: Publish Commander container on new builds

- examples/aws_lambda/lambda_handler.py
Our Lambda handler script returns an error in production, mainly due to Lambda's file system not allowing writing to other directories than /tmp. See more details below:
→ We import keepercommander without setting `HOME`, `TMPDIR `and `TEMP `environment variables, which would cause an issue as it would create pycache in user directory.
→ We call `api.login()`, which will attempt to create a .keeper/config.json file in user directory - which Lambda isn't allowed to do.
This change request introduces the following:
1. Complete overhaul of the lambda handler script
-Added `HOME`, `TMPDIR `and `TEMP `environment variables before import
-Added code that creates custom /tmp/.keeper/ dir to store the config file.
-Added code that leverages the `get_params_from_config()` function to store the …
> lambda_handler.py overhaul

- keepercommander/cli.py
- keepercommander/commands/utils.py
- keepercommander/service/commands/security_config_handler.py
- keepercommander/service/commands/service_config_handlers.py
This PR introduces support for a new `--file` flag to the `debug` command and `this-device` will show where is config.json file in Keeper Commander.  
The flag allows users to send all DEBUG-level logs to a specified file.
---
- **New flag:** `debug --file=/path/to/log`
- Creates (or switches to) a file handler that captures **all DEBUG logs**.
- Console output level is preserved (INFO/WARNING), so enabling file logging does not spam the terminal with debug lines.
- **config.json file**: `this-device`
- Now `this-device` command will show config.json file location.
---
```bash
debug --file=/tmp/debug.log
> Add --file flag for save debug logs to file

- keepercommander/commands/folder.py
- keepercommander/commands/record.py
- keepercommander/commands/record_edit.py
- keepercommander/commands/register.py
- keepercommander/enforcement.py
- keepercommander/params.py
- keepercommander/service/config/cli_handler.py
- keepercommander/service/util/command_util.py
* **Created `enforcement.py`**
* Implements master password re-entry enforcement policy for Commander with following behavior:
* Prompt for master password re-entry on record-level commands.
* If biometric authentication is available and configured → prompt for biometric.
* If 2FA is configured → bypass policy enforcement.
* If SSO login is configured → bypass policy enforcement.
* If SSO user also has master password or biometric setup → enforce those mechanisms.
* **Added Service Mode Support**
* Bypasses master password enforcement when running in service mode.
* Handles persistent login scenarios by dynamically fetching salt/iterations.
[KC-762]: https://keeper.atlassian.net/browse/KC-762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KC-762: Respect "MASTER_PASSWORD_REENTRY" enforcement.

- keepercommander/__main__.py
- keepercommander/command_categories.py
- keepercommander/commands/enterprise.py
- keepercommander/commands/record.py
- keepercommander/commands/register.py
- keepercommander/importer/commands.py
- **Added missing commands to help system:**
- `find-password` - Find and display password for a record
- `file-report` - File reporting functionality  
- `rm` - Remove/delete records
- `load-record-types` - Load custom record types from JSON file
- `audit-alert` - Manage audit alerts and notifications
- **Updated logger configuration:**
- Set logger name to `keepercommander` for consistent logging across the application and to enable external log level configuration for keepercommander-specific logs
> Add missing commands to help and update logger name
