- README.md
- config.json.sample
- setup.py
Now readme.md is converted to .rst format required for pypi listing
using pypandoc. Result - pypi listing looks cool!
> Setup and readme updated to display nicely on pypi

- .gitignore
- README.md
- keepercommander/__init__.py
- keepercommander/api.py
- requirements.txt
- setup.py
- Replace pycrypto with pycryptodomex.
- Ignore .DS_Store files.
- Minor edits to README.md for consistency.
> Windows compatibility update

- keepercommander/importer/json/json.py
The code already exported the uid of shared folders.  It makes sense
to export the uid of the records themselves as well!
> In `export`, add the `uid` of records.

- setup.py
> Replace manual packages declaration with find_packages in setup.py

- cloud9_setup.sh
Adding a file to make setting in cloud9 quick, simplier.
> Cloud9 setup script

- keepercommander/commands/msp.py
- keepercommander/display.py
- fixed bug with missing stash values when running `msp-info`
- fixed few typos in the documentation
> KS-117 - bug fix

- README.md
- keepercommander/commands/enterprise.py
Removed broken `enterprise-push` command and update readme to show example how `share-record` and `share-folder` works.
> Remove enterprise-push and updated readme

- keepercommander/__init__.py
- setup.py
Bumping protobuf version to 3.13.0 in `setup.py` file
> Bumping protobuf version to 3.13.0

- README.md
- keepercommander/__main__.py
- keepercommander/api.py
- keepercommander/loginv3.py
- keepercommander/params.py
- fixed login v3 SSO flow for On prem SSO login flow.
- fixed bug when trying to disable logging in w/ login v3 it will still use login v3 flow
- fixed README for login v3 example
> Login V3 SSO w/ Alternative Master Password 

- README.md
- keepercommander/commands/utils.py
- Fixing documentation for `this-device`
- Fix bug registering device
> Docs clean up and bug fix

- keepercommander/__init__.py
- keepercommander/commands/folder.py
- keepercommander/commands/record.py
- keepercommander/display.py
- keepercommander/importer/keepass/keepass.py
- fix documentation for `delete-attachment` doc
- workaround for the crash when exporting to keepass vault that has Shared Folder with the single quote
- added new `-v|--verbose`flag to `list`, `ls`, and `search` command to print full title and url
> Minor improvements

- keepercommander/loginv3.py
> sso alt mp 2fa login issue

- README.md
Added Security Audit Report help section
> Added Security Audit Report to README.md

- keepercommander/loginv3.py
> Ctrl+C or EOF (Ctrl+D/Z) will exit() on 2fa input

- keepercommander/commands/enterprise.py
Added Account Transfer Status column to following commands: `user-report`, `eu`, and `ei --users`
> Added Account Transfer Status column

- keepercommander/cli.py
- keepercommander/loginv3.py
Clarifying error message if used does not have permissions to access Commander
> Clarifying "Communication error" message

- keepercommander/__init__.py
- keepercommander/importer/csv/csv.py
- keepercommander/importer/json/json.py
> Fixing export functionality

- keepercommander/loginv3.py
> Fixed retrieval of the device id for `this-device` commands

- keepercommander/generator.py
Improve random password generation by using builtin python function for python 3.6+ and use legacy one for python any other python versions
> Improve password generation

- Makefile
- keepercommander/commands/enterprise.py
- keepercommander/commands/enterprise_pb2.py
> KC-176 create node isolation commands targeted

- keepercommander/cli.py
- keepercommander/commands/base.py
- keepercommander/commands/folder.py
- keepercommander/loginv3.py
Also improves the message when an incorrect password is entered.
> Kc 172 show descriptive error message when license or master pw expire

- keepercommander/cli.py
- keepercommander/commands/base.py
- keepercommander/commands/folder.py
- keepercommander/commands/utils.py
- keepercommander/loginv3.py
Backed out Dan's changes, added Sergey's
> KC-172-3-show-descriptive-error-message-when-license-or-master-pw-expire

- keepercommander/api.py
- keepercommander/cli.py
- keepercommander/commands/__init__.py
- keepercommander/commands/base.py
- keepercommander/commands/register.py
- keepercommander/commands/utils.py
- keepercommander/loginv3.py
- keepercommander/recordv3.py
Resolving circular reference introduced by adding record types.
> Resolving circular reference - KC-242

- keepercommander/__init__.py
- keepercommander/commands/utils.py
- Fixed adding app share with `secrets-manager` command
Bumping version to 16.1.7
> KSM: fix adding app share

- keepercommander/rest_api.py
Bumping Commander version to 16.1.8
> Manually downgrading client version to 16.1.6

- keepercommander/__init__.py
- keepercommander/rest_api.py
Reverting back client versioning to be relied on the version in __init__.py file
Bumping version to 16.1.9
> revert versioning

- keepercommander/cli.py
- keepercommander/constants.py
There were a few issues with recently merged PR #474 that are fixed by this PR:
- Fix a typo in the indentation in constants.py
- Fix the import order in cli.py that was causing an import error
> Fix issues with PR #474

- keepercommander/commands/utils.py
- Command to delete application
- Added ability to remove all clients at once using command `secrets-manager client rm --app [APP NAME or UID] --client *`
- Printing client IDs in a short format
- Documentation for ksm commands
> Ksm improvements

- .github/workflows/test-with-pytest.yml
- keepercommander/api.py
- keepercommander/commands/utils.py
- keepercommander/constants.py
- keepercommander/loginv3.py
- keepercommander/params.py
- unit-tests/test_api.py
- Add post login action for changing the master password
- Add post login action for accepting an account transfer if the deadline for accepting the transfer has expired
- Change the check-enforcements command to not block if the deadline for accepting an account transfer has not expired
- Add a new command "accept-transfer" that allows for accepting the transfer
> Add v3 post login actions (KC-259)

- keepercommander/commands/utils.py
- keepercommander/constants.py
- keepercommander/utils.py
- new flag to generate new client that will generate config in JSON or Base64
- one time tokens now contain hostname
> KSM: init config and token with host

- keepercommander/commands/record.py
- keepercommander/commands/recordv3.py
Just a couple of updates to record-history's help text.
> KC-260 record history command show that revision is required

- keepercommander/loginv3.py
Added support for cryptography 35.0.0 package by removing adding device_private_key to params as it is not used anywhere in the code
> - Support for cryptography 35.0.0 package

- keepercommander/plugins/ssh/ssh.py
- keepercommander/plugins/sshkey/sshkey.py
Changed ssh (unix password) and sshkey (RSA, etcetera auth).
> KC-155 ability to specify ssh port in the ssh plugin

- keepercommander/commands/recordv3.py
- keepercommander/commands/utils.py
- Fixing sync down for records that were removed with `--purge` flag
- Fixed properly removing KSM Application records
> Fix sync down on purge and proper removal of KSM Apps

- keepercommander/importer/imp_exp.py
- keepercommander/importer/lastpass/lastpass.py
This PR completes the import if the command is run again and there are missing attachments from records that are already imported.
> Upload missing attachments

- keepercommander/commands/recordv3.py
This PR fixes the attachment record link for the following commands:
- `upload-attachment`
- `add --attach`
> Fix upload-attachment and add with --attach option (KC-309)

- keepercommander/importer/lastpass/vault.py
This is a hotfix for an issue where a corrupt file attachment breaks the import.
> Skip corrupt file attachments

- keepercommander/commands/utils.py
KSM: added "Expires On" and coloring to `sm app get`
> KSM: added "Expires on"

- keepercommander/commands/utils.py
Command `version` added "(Current version)" if commander's version is the current version
> Added "Current version" to version command

- keepercommander/commands/utils.py
fixed generation of the one time token if the server is not in the list of predefined servers
> KSM: fixed one time token generation for dev server

- keepercommander/api.py
- keepercommander/importer/lastpass/account.py
- keepercommander/importer/lastpass/lastpass.py
- keepercommander/importer/lastpass/parser.py
This PR adds the importing of TOTP codes from LastPass
> Import TOTP codes from LastPass

- keepercommander/cli.py
- keepercommander/commands/base.py
- keepercommander/commands/scripting.py
This PR adds a run-batch command.
The command runs Commander commands from one or more files. File patterns are also accepted.
> Add run-batch command

- keepercommander/commands/register.py
Adding folder path to the record in `share-report`.
Example output:
```
My Vault> >? share-report -v -o
---  -----------------------  ----------------------  -------------------  --------------------------------  -----------------------------
1  Sub sub folder Record 1  FNpy1UzyHBKipoeD0g1AsQ  user1@keeperdemo.io  user2@keeperdemo.io -> Read Only  Folder 1/Sub folder 1
2  Health Test Record 1     zzKXCdkjvDLCTATrDPobpA  user1@keeperdemo.io  user2@keeperdemo.io => Read Only  Test Records
3  Health Test Record 2     SrN4nFyUrAv5rheJMh4z4Q  user1@keeperdemo.io  user2@keeperdemo.io => Read Only  Test Records
4  Some record              jvWFHnuT9DKyzefhWe-_jA  user1@keeperdemo.io  user2@keeperdemo.io -> Read Only
```
> Folder path in `share-report`

- keepercommander/plugins/commands.py
- keepercommander/plugins/ssh/ssh.py
This fixes the rotation command with adpasswd and ssh plugins.
> Fix rotation

- keepercommander/recordv3.py
This PR also adds a label to the record field if the field getting a new value has a unique type.
> Fix spelling and incorrect warning for missing fields when adding v3 record

- keepercommander/commands/utils.py
- keepercommander/generator.py
This PR adds automatic breachwatch detection to the password generator if breachwatch is enabled.
The following options are also added:
- `--number, -n` generates multiple passwords
- `--no-breachwatch, -nb` skip the breachwatch detection
> Add breatchwatch check and extra options to generate command

- keepercommander/commands/convert.py
- keepercommander/subfolder.py
Fix converting records that are under sub-folders in the shared folde…r (ex. `Shared Folder 1/Sub-Folder/Record1`).
> `convert` records under sub-folder

- keepercommander/commands/utils.py
Fixing error when shared folder is deleted but an application still has reference to it.
> KC-366: KSM - App info error on removed shared folder

- keepercommander/commands/enterprise_create_user.py
> create-user doesn't set display name to --name option

- keepercommander/commands/record.py
- keepercommander/commands/register.py
added features for above commands:
1) show team(s) to which each folder/record is shared 
2) flag/option to display members of each share team when possible
> share-report (w/ "--folders" flag) and shared-records-report team info

- keepercommander/commands/aram.py
- keepercommander/commands/enterprise.py
- keepercommander/sox/__init__.py
- keepercommander/sox/sox_data.py
- keepercommander/sox/sox_types.py
- keepercommander/sox/sqlite_storage.py
- keepercommander/sox/storage_types.py
- keepercommander/storage/sqlite.py
1) optimizations for sox data retrieval and storage, 
2) new syntax help text if no args passed (compliance-report)
3) added flag for deleting local filesystem cache upon command exit (compliance-report & aging-report)
4) additional filters (compliance-report)
5) additional output columns (compliance-report)
2nd BATCH of ADDITIONS / FIXES:
1) records w/o data now excluded from local data storage, 
2) removed async local db read/write ops, 
3) added clean-up of command tasks on SIGINT / SIGTERM 
4) improved anonymous/ non-enterprise userid hashing
> compliance-report / aging-report / SOX data filesystem-caching improvements

- keepercommander/commands/record.py
1) all teams now included for each record shared via share team folder 
2) better handling of team-not-found exception
> shared-records-report fixes: 

- keepercommander/commands/aram.py
1) add team filter option 
2) modify filter options help-text for clarity 
3) sort report rows so record-owner is listed 1st for shared records
> compliance-report additions/improvements: 

- keepercommander/commands/aram.py
1) fixed NoneType error bug in record title matching/filter
2) added support for filter by team UID
> compliance-report fix/improvement

- keepercommander/commands/aram.py
- keepercommander/commands/base.py
- keepercommander/commands/compliance.py
- keepercommander/commands/enterprise.py
1) add team-report as compliance subcommand
2) add user role-privilege validation to compliance reporting commands 
3) move compliance-reporting to own module
> compliance-report re-factor/add team-report feature: 

- keepercommander/commands/aram.py
- keepercommander/commands/transfer_account.py
1) add transfer admin action 
2) add user-confirmation prompt for irreversible actions (e.g., transfer, delete)
> action-report improvements: 

- keepercommander/commands/aram.py
- keepercommander/commands/compliance.py
- keepercommander/sox/__init__.py
1) use compliance data to provide more complete record-specific (title, url) audit-report output 
2) add more useful error message when user runs aging-report w/ compliance-report add-on disabled
> compliance data in ARAM (aging-report, audit-report) additions/improvements:

- keepercommander/commands/compliance.py
1) allow backend to search for record-access events triggered by deleted user 
2) show more useful error message when user not found
> compliance record-access-report fix/improvements: 

- keepercommander/commands/enterprise.py
> enterprise-role to support editing Account Transfer role enforcement

- keepercommander/commands/aram.py
1) preview of affected users in admin-action confirmation prompt
2) 'invited' user-status filter
3) validation and default-setting of command arg values (for non-CLI usage)
> action-report additions:

- keepercommander/__main__.py
- keepercommander/commands/record.py
- keepercommander/params.py
1) add config settings "unmask_all" and "fail_on_throttle" 
2) add corresponding "--unmask-all" and "--fail-on-throttle" CLI flags
> support for setting session-level output-masking and throttle-handling behaviors: 

- keepercommander/sox/__init__.py
enable compliance-reporting on all MCs for MSP admins
> compliance-reporting validation fix: 

- keepercommander/cli.py
add CommandError handling w/ output of error message
> batch-mode improvement: 

- keepercommander/api.py
- keepercommander/breachwatch.py
- keepercommander/commands/breachwatch.py
- keepercommander/commands/enterprise.py
- keepercommander/commands/record.py
- keepercommander/commands/recordv2.py
- keepercommander/commands/recordv3.py
- keepercommander/loginv3.py
- keepercommander/params.py
- keepercommander/utils.py
1) add "bw reset" command 
2) add support for calculating admin-side sec. scores using incremental data and saving results, 
3) add support for setting reused pw counts, 
4) add support for updating user-side security data on record events
> security audit score calculation improvements: 

- keepercommander/__init__.py
- keepercommander/commands/enterprise.py
1) include "login_console" events in "last_login" calculation (user-report command), 
2) change release version to 16.8.14
> user-report fix, release version update: 

- keepercommander/commands/enterprise.py
> external-shares-report: fix check for external users

- keepercommander/commands/enterprise.py
1) fix pagination bug
2) fix last_login values: now derived from "accept_invitation", "login", "login_console", and "chat_login" events
> user-report fixes (for JIRA KC-519):

- keepercommander/commands/enterprise.py
1) no-limit look-back-days 
2) infinite loop bug w/ empty usernames filter 
3) most-recent logins 
4) no-rows-returned bug
> user-report fixes (for KC-519):

- keepercommander/breachwatch.py
- keepercommander/commands/breachwatch.py
- keepercommander/commands/record.py
- keepercommander/commands/utils.py
additional fix/improvement: check for enterprise user before updating reused pw count
> feature: `sync-security-data` cmd

- keepercommander/commands/register.py
update security data prior to record ownership transfer
> `share-record` improvement: 

- keepercommander/commands/register.py
- keepercommander/shared_record.py
1) permissions accuracy 
2) team-user view
> `share-report` fixes/improvements:  (KC-536)

- keepercommander/commands/enterprise.py
add exception handling for failed share-removal commands (prevent aborting main command on fail)
> `external-shares-report` improvement: 

- keepercommander/commands/aram.py
add support for multiple `--event-type` option values
> `audit-report` improvement: 

- keepercommander/commands/compliance.py
- keepercommander/commands/enterprise.py
- keepercommander/sox/__init__.py
- keepercommander/sox/sqlite_storage.py
1) add support for limiting results to shared records (allow KA filtering)
2) modify commands that rely on compliance data for shared-records information to utilize filter in #1
> SOX compliance data improvement: 

- keepercommander/commands/record.py
- keepercommander/commands/register.py
- keepercommander/shared_record.py
1) permissions bug fix 
2) ordered team/member permissions
> `shared-records-report` improvements/fixes (KC-545):  

- keepercommander/commands/aram.py
1) add pagination support for administrative command batch-requests 
2) sync local enterprise data when changes are made (i.e., administrative action is taken for users in report)
> `action-report` improvements (KC-564):

- keepercommander/shared_record.py
exclude records not found in user's vault
> (KC-545) `keepercommander.get_shared_records()` fix: 

- keepercommander/commands/pam/router_helper.py
Gateway: Added support to print IP address of the gateway when calling gateway info action
> PAM Gateway CMD: Print gateway IPs

- keepercommander/commands/register.py
add support for removing duplicates
> `find-duplicate` improvement (KC-571):

- keepercommander/commands/aram.py
- keepercommander/sox/__init__.py
- keepercommander/sox/sqlite_storage.py
1) fix Last Password Change value to show most recent datetime 
2) fix bug w/ preliminary data being overwritten by compliance data update 
3) fix bugs w/ cached data update history 
4) add description of Aging Report results in title 
5) add 'shared' sort option 
6) add support for excluding deleted records from report
> `aging-report`/compliance data improvements/fixes (KC-563): 

- keepercommander/commands/aram.py
add support for filtering by "blocked" status and deleting the results
> (KC-587) `action-report` improvement: 

- keepercommander/sync_down.py
BreachWatch records cached data population on response data received
> (KC-593) sync-down fix: 

- keepercommander/commands/enterprise.py
add support for filtering by node(s)
> (KC-570) `security-audit-report` improvement: 

- keepercommander/commands/enterprise.py
add support for assigning role(s) to all accounts using the @all pseudo-user notation
> (KC-553) 'enterprise-user' improvement:

- keepercommander/commands/aram.py
1) add check for "auto_invite_user" event date for SCIM-provisioned accounts (for --target=invited) 
2) add check for "login_console", "chat_login", and "accept_invitation" events for --target=no-logon
> `action-report` improvements/fixes:

- keepercommander/commands/aram.py
- keepercommander/sox/sox_data.py
1) fixed bug w/ aging-data cache rebuild 
2) improved aging-data fetching efficiency
> (KC-635) `aging-report` fix/improvements: 

- keepercommander/sox/__init__.py
- keepercommander/sox/sox_data.py
- keepercommander/sox/sox_types.py
- keepercommander/sox/storage_types.py
add encryption of locally-stored sensitive data
> (KC-636) compliance data caching improvement: 

- keepercommander/commands/compliance.py
1) fixed bug w/ missing email for external users 
2) user email now derived from compliance data (to allow value to be shown for external users)
> (KC-641) `compliance shared-folder-report` fix/improvement: 

- keepercommander/api.py
add handler for server-side throttling (to ensure all data requested are received)
> (KC-643) api.execute_batch() improvement/fix

- keepercommander/commands/aram.py
- keepercommander/commands/enterprise.py
- keepercommander/commands/enterprise_common.py
1) fixed bug in `action-report` account deletion for # > 1000 
2) re-factored ActionReportCommand to use EnterpriseUserCommand for performing most administrative actions 
3) added batch allocation of new enterprise user ids (for adding new users) in EnterpriseUserCommand
> (KC-644) `action-report` + `enterprise-user` fixes/improvements: 

- keepercommander/commands/enterprise.py
- keepercommander/commands/security_audit.py
1) command info / help text 
2) remove debugging code
> (KC-653) `security-audit-report` minor fixes: 

- keepercommander/importer/imp_exp.py
0 records should be exported if specified folder(s) empty
> (KC-659) `export` fix: 

- keepercommander/commands/compliance.py
- keepercommander/sox/sox_data.py
- keepercommander/sox/sox_types.py
add breakdown of active vs. deleted records
> (KC-662) `compliance stats` improvement: 

- keepercommander/commands/compliance.py
Add option to explicitly use local cache (via `--no-rebuild` flag)
> (KC-667) `compliance-report` improvement: 

- keepercommander/commands/aram.py
make retrieval of additional record-detail data explicit
> (KC-691) `audit-report` improvement: 

- keepercommander/commands/utils.py
1) allow security-data update of TypedRecord instances 
2) remove "--hard" option
> (KC-692) `sync-security-data` fix + improvement: 

- keepercommander/commands/aram.py
add flag for excluding non-shared-folder records from report
> (KC-695) `aging-report` improvement: 

- keepercommander/cli.py
- keepercommander/commands/utils.py
- keepercommander/loginv3.py
- keepercommander/sync_down.py
1) replaced api.login() calls in cli.py with LoginCommand.execute() 
2) added SyncDownCommand().execute() call after login success in LoginCommand
3) moved BreachWatchScanCommand and SyncSecurityDataCommand calls from sync_down() to LoginCommand (after sync-down)
> (KC-702) `login`/`sync-down` fixes/improvements: 

- keepercommander/commands/enterprise.py
1) use `ei -u` command to get correct users list 
2) add indication of out-of-range or n/a last-login values
> (KC-704) `user-report` fix / improvements:

- keepercommander/cli.py
- keepercommander/commands/aram.py
- keepercommander/commands/base.py
1) added filter options `--share-folder-uid`, `--node-id`, `--days` 
2) optimized json export to minimize memory-usage
3) improved export progress indicator
4) improved execution cancellation-handling / clean-up functionality for all commands
> (KC-708) `audit-log` / command execution improvements / fixes:  

- keepercommander/breachwatch.py
update re-used password count for non-BW-enabled enterprise accounts on password-record edit/add/delete
> (KC-712) security-data/re-used passwords update bug-fix: 

- keepercommander/commands/aram.py
1) support for additional columns 
2) improved formatting 
3) additional user data in report by default
> (KC-671) action-report improvements / additions: 

- keepercommander/commands/aram.py
1) report limited to users in managed nodes 
2) improved formatting 
3) simplified and optimized audit event queries
> (KC-717) `action-report` improvements/bug-fixes: 

- keepercommander/commands/compliance.py
1) added `--deleted-items` and `--active-items` filter flags  
2) added "in_trash" report column
> (KC-718) `compliance-report` improvements: 

- keepercommander/commands/aram.py
- keepercommander/commands/compliance.py
- keepercommander/sox/sox_data.py
- keepercommander/sox/sox_types.py
- keepercommander/sox/storage_types.py
1) --report-type, --aging flags 
2) in_trash, has_attachments, record-aging data columns 
3) support for multiple users + "@all" pseudo-user
4) increased row limit for non-raw report-types in `audit-report`
> (KC-719) `compliance record-access-report` + other improvements:

- keepercommander/commands/discoveryrotation.py
- keepercommander/commands/tunnel/port_forward/endpoint.py
Add enable and disable for tunnel on record
Before making a tunnel check to see if it is enabled.
> Tunnel pam settings on record

- keepercommander/commands/breachwatch.py
- keepercommander/commands/security_audit.py
added `bw report` as alias for command
> (KC-473) `security-audit-report --breachwatch` improvement:

- keepercommander/commands/folder.py
- keepercommander/subfolder.py
1) added `--recursive` flag to `ls` to enable recursive search of sub-folders 
2) optimized helper function (`subfolder.get_contained_record_uids()`) recursive search algorithm 
3) added helper function (`subfolder.get_container_folder_uids()`) for recursively searching a folder for all contained sub-folders
> (KC-743) `ls` and related improvements/additions: 

- keepercommander/commands/compliance.py
- keepercommander/sox/__init__.py
- keepercommander/sox/sox_data.py
1) shared-folder records bug-fix, 
2) node-filter fix, 
3) share-admin permissions bug-fix
4) add empty vaults to report
> (KC-752) `compliance stats` bug-fixes/improvement: 

- keepercommander/commands/folder.py
1) add check for overlapping folder trees 
2) fix bug w/ copying subfolders w/ 0 records, 
3) fix bug w/ `--children` flag 
4) fix bug w/ recursive search not showing records of subfolders if parent folder has 0 records
> `transform-folder` / `ls -R` fixes  (KC-759): 

- keepercommander/commands/utils.py
update and apply current user's account summary data when command is invoked
> (KC-763) `sync-down` improvement: 

- keepercommander/__init__.py
- keepercommander/commands/aram.py
- keepercommander/commands/compliance.py
1) include non-invited users in `compliance stats` output, 
2) standardize char casing in emails for string comparison in `action-report` 
3) release version update
> (KC-765+) : `compliance stats` + `action-report` fixes/improvements

- keepercommander/commands/recordv3.py
…be deleted / modified (synonymous w/ custom record-tpe)
> `record-type` fix: allow any record-type w/ scope = RT_ENTERPRISE to be deleted / modified (synonymous w/ custom record-tpe)

- keepercommander/commands/base.py
- keepercommander/commands/connect.py
- keepercommander/vault_extensions.py
1) support for SSH using "pamMachine" records 
2) improved "pamMachine" record description (now includes username and host)
> (KC-766) `ssh` / `list` improvements: 

- keepercommander/commands/aram.py
1) add support for client-side filtering of report rows by keystring 
2) make `--report-type=raw` default -- obviate need to specify option w/ each command call for raw event data queries
> `audit-report` improvements: 

- keepercommander/commands/enterprise.py
roles assigned via team-membership now included in "roles" field (roles + teams data now derived from EnterpriseInfoCommand output)
> (KC-775) `user-report` improvement:

- keepercommander/commands/ssh_agent.py
Adjust minimum key size allowed to accommodate valid ed25519 keys (can be as small as 119 bytes)
> `ssh-agent` improvement (KC-783): 

- keepercommander/commands/record_edit.py
- keepercommander/commands/security_audit.py
Output detailed error report when security summary data parsing/updating fails
Fix for error thrown when editing simple record field value
> (KC-788)`security-audit-report` improvement + `record-update` fix:

- keepercommander/commands/breachwatch.py
show (and save) updated summary scores
> (KC-796) `breachwatch report` Improvement: 

- keepercommander/commands/security_audit.py
Add support for resetting vaults w/ invalid security data
> `security-audit-report` Improvement (KC-805):

- keepercommander/commands/folder.py
remove share permissions from old share-folders prior to deleting
> (KC-807) `transform-folder` fix: 

- keepercommander/commands/enterprise.py
re-add option to skip confirmation prompts to allow non-interactive batch-scripting
> `enterprise-role` improvement (KC-807)

- keepercommander/commands/discover/__init__.py
Chanegd hostnameOrIPAddress to pamHostname to render the field correctly.
> DR-823 Fix field formattting for pamHostname

- keepercommander/importer/commands.py
- keepercommander/importer/cyberark/__init__.py
- keepercommander/importer/cyberark/cyberark.py
Add a module that imports accounts from CyberArk using the REST API
> CyberArk Account import functionality

- keepercommander/commands/msp.py
fix avg. licenses per day value for non-company + non-daily reports
add "initial_licenses", "final_licenses" columns for non-daily reports
> `msp-billing-report` fix + improvement (KC-833)

- keepercommander/commands/msp.py
Fix for error thrown when reporting by MC (accounts for possibly missing data for each MC)
> `msp-billing-report` bug-fix (KC-834)

- keepercommander/commands/discoveryrotation.py
- keepercommander/proto/router_pb2.py
Added NOOP option to PAM rotation edit command
> Added NOOP option to pam rotation edit command

- keepercommander/importer/cyberark/cyberark.py
Update the logic to submit a client_credentials request to the /oauth2/platformtoken endpoint.
It will prompt for the identity-tenent-id and the username/password for the service user.
> Add support for CyberArk Privileged Access Cloud

- keepercommander/api.py
- keepercommander/commands/compliance.py
- keepercommander/commands/record.py
API call optimizations, 
better throttle-handling, 
bug-fix for crash when deleted record shared-folder parent has no sub-folders
add "shared_folder_uid" column to `compliance-report`
> (KC-845 + KC-846) `compliance rar` + `compliance-report` + server-side-throttling improvements; `trash restore` fix

- keepercommander/commands/discoveryrotation.py
Added `pam connection` command
Improved most `pam ...` commands to resolve UID from path
> Added pam connection command

- keepercommander/commands/breachwatch.py
- keepercommander/commands/password_report.py
- keepercommander/commands/record.py
- keepercommander/team.py
1) `password-report`: fixed bug with folder path input, 
2) `list-team`: added option to list team members 
3) `bw list`: added format and output options
> KC-847, KC-848, KC-852

- keepercommander/api.py
- keepercommander/commands/ksm.py
- keepercommander/commands/register.py
- keepercommander/params.py
add `--contacts-only` option for allowing search for contacts with alternate domains
minor fix for `secrets app share`
> `share-record` Improvement + `secrets app share` fix (KC-853)

- keepercommander/commands/compliance.py
- keepercommander/commands/helpers/reporting.py
- keepercommander/commands/utils.py
compliance-reporting: Support for multi-keyword and reg-ex search
`sync-security-data`: Fix for KA error on security-data update for non-existent objects
> (KC-855) Misc. fixes

- keepercommander/importer/cyberark/cyberark.py
1. Use tabulate to list imported and skipped accounts
2. Use prompt_toolkit to implement retry/skip/abort
3. Print errors and return instead of raising exceptions
> Improve output and error handling

- keepercommander/importer/cyberark/cyberark.py
- Provide a reason to avoid 400 Bad Request getting passwords that require a reason
- Handle all errors from 400 to 500 by offering to skip or skip all
- Avoid throwing an exception so that the shell does not exit on error
> Support reason for access and other errors without exiting.

- keepercommander/commands/folder.py
- keepercommander/record_types.py
added parent folder UID to folder details
added new PAM field types (RBI)
> ls folder details - include parent uid

- keepercommander/importer/cyberark/cyberark.py
- Use 'in' instead of hasattr()
- Create all records in Shared Folders named after the Safe containing them
- Convert BusinessWebsite Platform (from Workforce Password Manager) to login records
- Prefix username with LoginDomain when it is present
> Cyberark enhancements

- keepercommander/api.py
- keepercommander/commands/aram.py
Include relevant events for contained records when shared-folder is specified in filter
> `audit-report` Improvement (KC-867)

- keepercommander/commands/discoveryrotation.py
Introduced a new column for gateway version in the `pam gateway list` command. Enhanced verbose mode to display detailed gateway version information, including OS and hardware details.
> KC-869: Add gateway version and detailed info to gateway list command

- keepercommander/commands/record.py
- keepercommander/commands/register.py
fix for incomplete team list for orgs w/ > 500 teams
> `list-team` + `share-folder` teams: 

- keepercommander/importer/cyberark/cyberark.py
- Add environment variables for login credentials
- Refactor to import safe by safe from an optional list
- Use the API error code instead of HTTP status for "Skip All"
> Cyberark safe centric

- keepercommander/importer/cyberark/cyberark.py
Add a delay between requests to avoid API rate limits.
> Cyberark delay

- keepercommander/commands/record.py
- **Bug Fix**: Fixed team deduplication when 500+ teams exist (was checking 'uid' instead of 'team_uid')
- **Feature**: Added `--sort` option to `list-team` command
- `--sort company` (default) - Sort by enterprise/company name
- `--sort team_uid` - Sort by team UID  
- `--sort name` - Sort by team name
> List teams improvements

- keepercommander/commands/ksm.py
Prevent sharing of app-secret when relevant current-user permissions don't allow for it
> KSM app-sharing bug-fix (KC-909)

- keepercommander/importer/cyberark_portal/cyberark_portal.py
- Enable federated login, e.g., Okta using OAuth2 w/ PKCE
- Import the Password SecuredItemType as a login record
- Import tags as a comma-separated list
- Output a table of the data to be imported
- Improve error messages
>  Add support for federated/SSO login, CyberArk Passwords and Tags

- setup.cfg
Updated the setup.cfg for winrt import
> Update setup.cfg import for winrt

- keepercommander/commands/enterprise_common.py
Add fallback logic for node display names (KC-949)
> Add fallback logic for node display names

- Dockerfile
- keepercommander/service/api/command.py
- keepercommander/service/config/file_handler.py
- keepercommander/service/config/service_config.py
- keepercommander/service/core/process_info.py
- keepercommander/service/core/service_app.py
- keepercommander/service/core/service_manager.py
- keepercommander/service/util/tunneling.py
- Configure Docker to run as non-root user for improved security (creates `commander` user with UID/GID 1000)
- Update background process import path and remove unused imports across service modules
> Fix Docker non-root user build and background mode import issues

- keepercommander/__main__.py
- keepercommander/commands/utils.py
- keepercommander/service/app.py
- keepercommander/service/core/service_manager.py
- keepercommander/service/util/parse_keeper_response.py
This commit addresses several issues and enhancements in the Keeper Commander service mode and CLI functionality:
- **CLI Argument Parsing**: Fixed main argument parser that was incorrectly reconstructing command arguments, causing service-create to fail with 'argument -p/--port: expected one argument'. The parser now preserves original argument order instead of splitting and reordering them.
- **Service Startup URL**: Fixed service startup message to correctly display http:// when SSL is disabled and https:// when SSL is enabled, based on the actual SSL certificate configuration.
- **SSL Error Messages**: Improved user experience by replacing ugly SSL handshake error messages ('Bad request version À\x13À') with clear, user-friendly messages when HTTPS requests are made to HTTP services. …
> feat: Improve service mode functionality and CLI usability

- keepercommander/__main__.py
This commit fixes the argument parsing issue introduced in commit 8100dc2d where global arguments (like --config, --server, --debug) appearing after command names were incorrectly passed to subcommand parsers.
The fix:
- Preserves original argument order to maintain proper flag/value pairing
- Filters out all main parser arguments before reconstruction
- Handles both --arg=value and --arg value formats
- Properly quotes all arguments using shlex.quote()
Fixes commands like:
- keeper record-add --config='config.json' -t 'Title' -rt login ...
- keeper record-add --debug --server='host' -t 'Title' ...
This resolves the 'unrecognized arguments' errors while maintaining the original fix for service-create command issues.
> fix: Complete argument parsing fix for commands with global arguments
